lvgl:
  pages:
    - id: settings_page
      bg_color: color_black
      scrollable: false
      hidden: false
      widgets:
        - obj:
            id: settings_info_page_keypad
            x: 15
            y: 15
            bg_color: color_steel_blue
            bg_opa: cover
            width: 690
            height: 650
            shadow_opa: transp
            border_opa: transp
            border_width: 0
            radius: 15
            widgets:
              - obj:
                  id: settings_widget
                  width: 660
                  height: 330
                  y: 0
                  align: top_mid
                  clickable: false
                  radius: 15
                  pad_all: 0
                  bg_color: color_slate_blue_gray
                  bg_opa: transp
                  border_opa: transp
                  border_width: 0
                  shadow_opa: transp
                  widgets:
                    - obj:
                        id: backlight_settings_brightness_background
                        width: 315
                        height: 140
                        align: top_left
                        clickable: false
                        radius: 15
                        pad_all: 0
                        bg_color: color_slate_blue_gray
                        border_opa: transp
                        border_width: 0
                        shadow_opa: transp
                        widgets:
                          - label:  
                              id: backlight_settings_brightness_label
                              y: 15
                              align: top_mid
                              text_font: nunito_28
                              text_color: color_misty_blue
                              text: "Backlight"
                          - slider:
                              id: backlight_settings_brightness_slider
                              y: 25
                              radius: 15
                              bg_color: color_gray
                              align: center
                              width: 210
                              height: 50
                              min_value: 35
                              max_value: 100
                              value: 100
                              indicator:
                                bg_color: color_misty_blue
                                radius: 15
                              knob:
                                bg_opa: transp
                              #on_release:
                              #  - light.turn_on:
                              #      id: display_backlight
                              #      brightness: !lambda return int(x)/ 100.0;
                    - obj:
                        id: backlight_settings_languages_background
                        width: 315
                        height: 175
                        align: bottom_left
                        clickable: false
                        radius: 15
                        pad_all: 0
                        bg_color: color_slate_blue_gray
                        border_opa: transp
                        border_width: 0
                        shadow_opa: transp
                        widgets:
                          - button:
                              id: settings_widget_lang_btn
                              width: 110
                              height: 110
                              pad_all: 0
                              align: center
                              clickable: true
                              border_opa: transp
                              bg_opa: transp
                              shadow_opa: transp
                              checked:
                                bg_opa: transp
                              widgets:
                                - image:
                                    id: settings_widget_lang_flag
                                    align: center
                                    src: flags_gb_img
                              #on_click:
                              #  - switch.toggle: language_switch
                    - obj:
                        id: backlight_settings_sleep_time_background
                        width: 330
                        height: 330
                        align: top_right
                        clickable: false
                        radius: 15
                        pad_all: 0
                        bg_color: color_slate_blue_gray
                        border_opa: transp
                        border_width: 0
                        shadow_opa: transp
                        widgets:
                          - label:  
                              id: backlight_settings_sleep_time_label
                              y: 30
                              align: top_mid
                              text_font: nunito_28
                              text_color: color_misty_blue
                              text: "Sleep time"
                          - roller:
                              id: backlight_settings_sleep_time_roller
                              y: 15
                              width: 210
                              align: center
                              bg_opa: transp
                              border_opa: transp
                              shadow_opa: transp
                              text_font: nunito_30
                              text_color: color_slate_blue_gray
                              text_line_space: 6
                              selected:
                                bg_opa: transp
                                text_font: nunito_30
                                text_color: color_misty_blue
                              #selected_index: !lambda return id(display_timeout);
                              options:
                                - Never
                                - 1 minute
                                - 5 minutes
                                - 10 minutes
                                - 30 minutes
                                - 1 hour
                                - 6 hours
                                - 12 hours
                              visible_row_count: 2
                              #on_value:
                              #    then:
                              #      - number.set:
                              #          id: display_timeout_backlight
                              #          value: !lambda |-
                              #            static const int backlight_time[] = {-1, 1, 5, 10, 30, 60, 360, 720};
                              #            return backlight_time[x];
                              #      - globals.set:
                              #          id: display_timeout
                              #          value: !lambda return x;
                              #      - delay: 300ms
                              #      - lambda: |-
                              #          ESP_LOGI("TEST", "Current DT global: %d", id(display_timeout));
              - obj:
                  id: info_widget
                  width: 660
                  height: 280
                  align: bottom_mid
                  clickable: false
                  radius: 15
                  pad_all: 0
                  bg_color: color_slate_blue_gray
                  bg_opa: cover
                  border_opa: transp
                  border_width: 0
                  shadow_opa: transp
                  widgets:
                    - label:
                        x: 30
                        y: 10
                        id: info_widget_cpu_label
                        align: top_left
                        text_font: nunito_28
                        text_color: color_misty_blue
                        text: "CPU"
                    - label:
                        x: -30
                        y: 10
                        id: info_widget_cpu_state_value
                        align: top_right
                        text_font: nunito_28
                        text_color: color_misty_blue
                        text: "38.5°"
                    - label:  
                        id: wifi_signal_info_label
                        x: 30
                        y: 60
                        align: top_left
                        text_font: nunito_28
                        text_color: color_misty_blue
                        text: "WiFi Signal:"
                    - label:  
                        id: wifi_signal_info_state
                        x: -30
                        y: 60
                        align: top_right
                        text_font: nunito_28
                        text_color: color_misty_blue
                        text: "-59 dBm"
                    - label:  
                        id: ip_address_info_label
                        x: 30
                        y: 115
                        align: top_left
                        text_font: nunito_28
                        text_color: color_misty_blue
                        text: "IP Address:"
                    - label:  
                        id: ip_address_info_state
                        x: -30
                        y: 115
                        align: top_right
                        text_font: nunito_28
                        text_color: color_misty_blue
                        text: "192.168.0.10"
                    - label:  
                        id: mac_address_info_label
                        x: 30
                        y: 170
                        align: top_left
                        text_font: nunito_28
                        text_color: color_misty_blue
                        text: "MAC Address:"
                    - label:  
                        id: mac_address_info_state
                        x: -30
                        y: 170
                        align: top_right
                        text_font: nunito_28
                        text_color: color_misty_blue
                        text: "12:34:56:78:90:AB"
                    - label:  
                        id: esphome_version_info_label
                        x: 30
                        y: 225
                        align: top_left
                        text_font: nunito_28
                        text_color: color_misty_blue
                        text: "ESPHome Version:"
                    - label:  
                        id: esphome_version_info_state
                        x: -30
                        y: 225
                        align: top_right
                        text_font: nunito_28
                        text_color: color_misty_blue
                        text: "2026.2.4"
        # back
        - obj:
            id: back_button_container
            y: 0
            width: 120
            height: 105
            align: bottom_mid
            bg_opa: transp
            pad_all: 0
            border_opa: transp
            border_width: 0
            shadow_opa: transp
            radius: 0
            widgets:
              - obj:
                  y: -30
                  width: 120
                  height: 8
                  align: bottom_mid
                  bg_color: color_steel_blue
                  pad_all: 0
                  border_opa: transp
                  border_width: 0
                  shadow_opa: transp
                  radius: 23 
            #on_click:
            #  - lvgl.widget.hide: alarm_panel_select_widget
            #  - lvgl.page.show: alarmo_card_page

######TODO decommentare quando verrano gestite le traduzioni dinamiche
#script:
#
#  - id: update_settings_translations
#    then:
#      - lvgl.label.update:
#          id: backlight_settings_brightness_label
#          text: !lambda |-
#            return id(i18n_translations).translate("settings.backlight");
#      - lvgl.label.update:
#          id: backlight_settings_sleep_time_label
#          text: !lambda |-
#            return id(i18n_translations).translate("settings.sleep_time");
#      - lvgl.label.update:
#          id: wifi_signal_info_label
#          text: !lambda |-
#            return id(i18n_translations).translate("settings.wifi_signal");
#      - lvgl.label.update:
#          id: ip_address_info_label
#          text: !lambda |-
#            return id(i18n_translations).translate("settings.ip_address");
#      - lvgl.label.update:
#          id: mac_address_info_label
#          text: !lambda |-
#            return id(i18n_translations).translate("settings.mac_address");
#      - lvgl.label.update:
#          id: esphome_version_info_label
#          text: !lambda |-
#            return id(i18n_translations).translate("settings.esphome_version");
#               
#      - lambda: |-
#          lv_obj_t *roller_obj = id(backlight_settings_sleep_time_roller).obj;
#          if (roller_obj == nullptr) {
#            return;
#          }
#
#          uint16_t old_selection = lv_roller_get_selected(roller_obj);
#
#          std::string options = 
#            id(i18n_translations).translate("sleep_time.never") + "\n" +
#            id(i18n_translations).translate("sleep_time.minute1") + "\n" +
#            id(i18n_translations).translate("sleep_time.minute5") + "\n" +
#            id(i18n_translations).translate("sleep_time.minute10") + "\n" +
#            id(i18n_translations).translate("sleep_time.minute30") + "\n" +
#            id(i18n_translations).translate("sleep_time.hour1") + "\n" +
#            id(i18n_translations).translate("sleep_time.hour6") + "\n" +
#            id(i18n_translations).translate("sleep_time.hour12");
#
#          lv_roller_set_options(roller_obj, options.c_str(), LV_ROLLER_MODE_NORMAL);
#          lv_roller_set_selected(roller_obj, old_selection, LV_ANIM_OFF);
