lvgl:
  pages:
    - id: settings_page
      bg_color: color_black
      scrollable: false
      hidden: false
      widgets:
        - obj:
            id: settings_info_page_keypad
            x: 15
            y: 15
            bg_color: color_slate_blue_gray
            bg_opa: cover
            width: 690
            height: 640
            shadow_opa: transp
            border_opa: transp
            border_width: 0
            radius: 15
            widgets:
              - obj:
                  id: settings_widget
                  width: 660
                  height: 330
                  y: 0
                  align: top_mid
                  clickable: false
                  radius: 15
                  pad_all: 0
                  bg_color: color_steel_blue
                  bg_opa: transp
                  border_opa: transp
                  border_width: 0
                  shadow_opa: transp
                  widgets:
                    - obj:
                        id: backlight_settings_brightness_background
                        width: 315
                        height: 140
                        align: top_left
                        clickable: false
                        radius: 15
                        pad_all: 0
                        bg_color: color_steel_blue
                        border_opa: transp
                        border_width: 0
                        shadow_opa: transp
                        #widgets:
                        #  - label:  
                        #      id: backlight_settings_brightness_label
                        #      y: 30
                        #      align: top_mid
                        #      text_font: nunito_28
                        #      text_color: color_misty_blue
                        #      text: "Backlight"
                        #  - slider:
                        #      id: backlight_settings_brightness_slider
                        #      y: 30
                        #      radius: 15
                        #      bg_color: color_gray
                        #      align: center
                        #      width: 210
                        #      height: 60
                        #      min_value: 35
                        #      max_value: 100
                        #      value: 100
                        #      indicator:
                        #        bg_color: color_misty_blue
                        #        radius: 15
                        #      knob:
                        #        bg_opa: transp
                        #      #on_release:
                        #      #  - light.turn_on:
                        #      #      id: display_backlight
                        #      #      brightness: !lambda return int(x)/ 100.0;
                    - obj:
                        id: backlight_settings_languages_background
                        width: 315
                        height: 175
                        align: bottom_left
                        clickable: false
                        radius: 15
                        pad_all: 0
                        bg_color: color_steel_blue
                        border_opa: transp
                        border_width: 0
                        shadow_opa: transp
                        #widgets:
                        #  - button:
                        #      id: settings_widget_lang_btn
                        #      width: 110
                        #      height: 110
                        #      pad_all: 0
                        #      align: center
                        #      clickable: true
                        #      border_opa: transp
                        #      bg_opa: transp
                        #      shadow_opa: transp
                        #      checked:
                        #        bg_opa: transp
                        #      widgets:
                        #        - image:
                        #            id: settings_widget_lang_flag
                        #            align: center
                        #            src: flags_it_img
                        #      #on_click:
                        #      #  - switch.toggle: language_switch
                    - obj:
                        id: backlight_settings_sleep_time_background
                        width: 330
                        height: 330
                        align: top_right
                        clickable: false
                        radius: 15
                        pad_all: 0
                        bg_color: color_steel_blue
                        border_opa: transp
                        border_width: 0
                        shadow_opa: transp
                        #widgets:
                        #  - label:  
                        #      id: backlight_settings_sleep_time_label
                        #      y: 30
                        #      align: top_mid
                        #      text_font: nunito_28
                        #      text_color: color_misty_blue
                        #      text: "Sleep time"
                        #  - roller:
                        #      id: backlight_settings_sleep_time_roller
                        #      y: 15
                        #      width: 210
                        #      align: center
                        #      bg_opa: transp
                        #      border_opa: transp
                        #      shadow_opa: transp
                        #      text_font: nunito_30
                        #      text_color: color_steel_blue
                        #      text_line_space: 6
                        #      selected:
                        #        bg_opa: transp
                        #        text_font: nunito_30
                        #        text_color: color_misty_blue
                        #      #selected_index: !lambda return id(display_timeout);
                        #      options:
                        #        - Never
                        #        - 1 minute
                        #        - 5 minutes
                        #        - 10 minutes
                        #        - 30 minutes
                        #        - 1 hour
                        #        - 6 hours
                        #        - 12 hours
                        #      visible_row_count: 1
                        #      #on_value:
                        #      #    then:
                        #      #      - number.set:
                        #      #          id: display_timeout_backlight
                        #      #          value: !lambda |-
                        #      #            static const int backlight_time[] = {-1, 1, 5, 10, 30, 60, 360, 720};
                        #      #            return backlight_time[x];
                        #      #      - globals.set:
                        #      #          id: display_timeout
                        #      #          value: !lambda return x;
                        #      #      - delay: 300ms
                        #      #      - lambda: |-
                        #      #          ESP_LOGI("TEST", "Current DT global: %d", id(display_timeout));
              - obj:
                  id: info_widget
                  width: 660
                  height: 270
                  align: bottom_mid
                  clickable: false
                  radius: 15
                  pad_all: 0
                  bg_color: color_steel_blue
                  bg_opa: cover
                  border_opa: transp
                  border_width: 0
                  shadow_opa: transp
        # back
        - obj:
            id: back_button_container
            y: 0
            width: 120
            height: 105
            align: bottom_mid
            bg_opa: transp
            pad_all: 0
            border_opa: transp
            border_width: 0
            shadow_opa: transp
            radius: 0
            widgets:
              - obj:
                  y: -30
                  width: 120
                  height: 8
                  align: bottom_mid
                  bg_color: color_slate_blue_gray
                  pad_all: 0
                  border_opa: transp
                  border_width: 0
                  shadow_opa: transp
                  radius: 23 
            #on_click:
            #  - lvgl.widget.hide: alarm_panel_select_widget
            #  - lvgl.page.show: alarmo_card_page
