packages:
  settings: !include common/pages/settings.yaml
  alarm_panel: !include pages/alarm_panel/alarm_panel.yaml

image: !include common/images.yaml
font: !include common/fonts.yaml
color: !include common/colors.yaml
substitutions: !include common/substitutions.yaml

external_components:
  - source: 
      type: local
      path: components
    components: [i18n]

esphome:
  name: simulatore-waveshare

# RIMUOVI o COMMENTA QUESTO:
# esp32:
#   board: esp32-p4-ev-board

# AGGIUNGI QUESTO:
host:

display:
  - platform: sdl
    id: my_display
    dimensions: 720x720

lvgl:
  id: lvgl_component
  buffer_size: 100%
  byte_order: little_endian